---
# tasks file for umask

# May be more approprate for Redhat distributions as they have umask defaults for system users and for regular users
- name: "template distributions umask startup file"
  template:
    backup: yes
    src: '{{ ansible_distribution }}/{{ ansible_distribution_major_version }}{{ umask_system_config_file_path }}.j2'
    dest: '{{ umask_system_config_file_path }}'
  when: ansible_os_family == 'RedHat'

# May be more appropriate for Debian distibutions as they have a global umask by default
- name: Replace all instances of UMASK in the umask systems wide configuration file
  replace:
    regexp: '^UMASK(\s+.*)'
    replace: 'UMASK		{{ umask_default_umask }}'
    dest: '{{ umask_system_config_file_path }}'
    mode: 0644
  when: ansible_os_family  == 'Debian'

# Other distribution os families:
# Alpine
# Archlinux
# Debian
# Gentoo
# RedHat
# Suse
