---
# tasks file for umask

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/login.defs
    dest: /etc/login.defs_backup
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Replace UMASK setting with our own
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK'
    line: 'UMASK		{{ umask_default_umask }}'
    owner: root
    group: root
    mode: '0644'

# Other distribution os families:
# Alpine
# Archlinux
# Debian
# Gentoo
# RedHat
# Suse
