---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  #- name: "umask-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
  - name: "umask-${image:-centos}-${tag:-7}${TOX_ENVNAME}"
    #image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    image: "${namespace:-robertdebock}/${image:-centos}:${tag:-7}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
